services:

#  custom-app:
#    image: basic_devsecops:v1
#    restart: always
#    depends_on:
#      - mongodb
#    environment:
#      MONGODB_USER: ${MONGODB_USER}
#      MONGODB_PASS: ${MONGODB_PASS}
#      MONGODB_HOST: ${MONGODB_HOST}
#      MONGODB_PORT: ${MONGODB_PORT}


  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASS}
    volumes:
      - mongo_data:/data/db


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL}


volumes:
  mongo_data:
